### ISSUE TITLE
React Router v6

### ISSUE THREAD

**Issue by seanblonien** [kruschid/typesafe-routes#14]
I am currently using this library and have loved type-safe routing every since (and would hate going back to using plain react-router).

Is there a plan to update this library to be compatible with React Router v6?

I have been using this library so I have not used v6 and can't speak to the advantages of it directly over v5, BUT, from what I have seen describing v6, the emphasis on hooks (which, to be fair is already in v5), the \<Routes\> replacing \<Switch\>, portals, and generally the \<Route\> component and how it handles nested routes looks pretty promising.

**Comment by kruschid** [comment]
Thank you for your feedback @seanblonien. Sure I will try to make it compatible to v6. Next week I will take a look at it. So far the changes of v6 are looking promising to me (e.g relative routes). Could be worth to use it for new projects.

**Comment by seanblonien** [comment]
@kruschid any update a few months later?

**Comment by kruschid** [comment]
> @kruschid any update a few months later?

@seanblonien thank you for reminding me. Yes, you could try the latest commit in master. It's possible to create relative routes now (useful if you want nested routes in v6). I also added a new section "Absolute & Relative Routes" to the repo README.

For now you can use it by adding `"typesafe-routes": "https://github.com/kruschid/typesafe-routes.git"` to your `package.json`. I will publish it on npm after a few more tests. Just let me know what you think. Thank you.

**Comment by kruschid** [comment]
Published a version with v6 support a while ago.  :-)
