### ISSUE TITLE
getting bunch of errors when used with storybook

### ISSUE THREAD

**Issue by Srujna** [kruschid/typesafe-routes#15]
I have a component where I have used useRouteParams of 'typesafe-routes/react-router'
Component working fine however when I try to add this component to a storybook story, it is failing:

![image](https://user-images.githubusercontent.com/22705741/152352088-d1641719-64a8-47fe-8391-70b82eb05212.png)
![image](https://user-images.githubusercontent.com/22705741/152352180-0f720db5-691f-4fb1-8b63-3b6708bbcb63.png)

**Comment by Srujna** [comment]
Can you please guide me where I am going wrong

**Comment by kruschid** [comment]
Hi @Srujna, it's a little difficult to say without seeing your code. But generally `useRouteParams` doesn't reference the `location` prop directly it rather depends on the react router context. Are you sure your storybook is running it within the said context?
