### ISSUE TITLE
Has a dependency on react/react-router

### ISSUE THREAD

**Issue by anilanar** [kruschid/typesafe-routes#28]
`index.ts` re-exports `react-router.ts`, which depends on `react` and `react-router-dom`. So if a project doesn't have those dependencies, then it's impossible to use `typesafe-routes`.

I suggest `react-router` related dependencies are not re-exported from `index.ts`. So users that want to use `react-router` utilities can import it as `typesafe-routes/react-router` instead.

**Comment by anilanar** [comment]
Workaround:

```
import { route } from "typesafe-routes//build/route";
import { intParser } from "typesafe-routes//build/parser";
```

**Comment by kruschid** [comment]
thanks for reporting, I'll take a look.

**Comment by kruschid** [comment]
> I suggest `react-router` related dependencies are not re-exported from `index.ts`. So users that want to use `react-router` utilities can import it as `typesafe-routes/react-router` instead.

Yep that's exactly how it's implemented now in the latest update. Thanks again.
