### ISSUE TITLE
Angular - Optional parameters aren't counted as parameters

### ISSUE THREAD

**Issue by Indeedornot** [kruschid/typesafe-routes#35]
## Issue
When using this library with Angular and making parameters optional
e.g.
```ts
	public static orders = {
		show: route('orders/:id?', { id: intParser }, {})
	};
```

and registering such route as so
```ts
const routes = [
	// Orders
	{
		path: AppRoutes.orders.show.template,
		component: OrdersPageComponent
	}
}
```

the route is indentified as so
`orders/:id`
where `:id` is a string rather than a parameter

## Possible workaround

Using a preprocessing function that preprocesses the paths before giving them to Angular to register

```ts
const getRoute = (route: RouteNode<string, any, any>) => {
	//remove all instances of '?' from route
	if (route.template.includes('?')) {
		return route.template.replace(/\?/g, '');
	}

        return route.template;
}
```

and using it instead of the clear template

```ts
const routes = [
	// Orders
	{
		path: getRoute(AppRoutes.orders.show),
		component: OrdersPageComponent
	}
}
```

#### 2. Moving the optional declaration onto the ParserMap e.g.
  ```ts
	public static orders = {
		show: route('/orders/:id', { id?: intParser }, {})
	};
  ```

**Comment by kruschid** [comment]
I'm not very familiar with optional parameters in Angular. However, if you're suggesting that it's possible to leave a parameter undefined that is specified in a template, then it could potentially be solved with a custom template rendering function. However, this would require an upgrade to version 12.

Consider the `renderTemplate` function from the [Angular Router example given here](https://github.com/kruschid/typesafe-routes/blob/93e15b4fd1c786718c40e5879abcf94016a0a1c2/examples/angular-router/src/renderer.ts#L26-L34). The returned templates don't have optional parameters with a trailing `?` character.

``` ts
const renderTemplate = ({ pathSegments }: AnyRenderContext) => {
  const template = pathSegments
    .map((pathSegment) =>
      typeof pathSegment === "string" ? pathSegment : `:${pathSegment.name}`
    )
    .join("/");

  return template; // path that doesn't start with a slash "/" character
};
```

You can refer to [this documentation](https://github.com/kruschid/typesafe-routes/blob/3f3134482cadd2c29bc371c0a4770331143b98a3/docs/customization/custom-template-rendering.md) on how to use custom rendering functions.

Thanks for the feedback.
