### ISSUE TITLE
PeerDependency

### ISSUE THREAD

**Issue by Xample** [kruschid/typesafe-routes#41]
Hello, after installing the lib (npm i typesafe-routes)
I got the following warning:

npm WARN Could not resolve dependency:
npm WARN peer [typescript@"^4.1.0](mailto:typescript@%22%5e4.1.0)" from [typesafe-routes@10.0.5](mailto:typesafe-routes@10.0.5)
npm WARN node_modules/typesafe-routes
npm WARN   typesafe-routes@"*" from the root project
npm WARN
npm WARN Conflicting peer dependency: [typescript@4.9.5](mailto:typescript@4.9.5)
npm WARN node_modules/typescript
npm WARN   peer [typescript@"^4.1.0](mailto:typescript@%22%5e4.1.0)" from [typesafe-routes@10.0.5](mailto:typesafe-routes@10.0.5)
npm WARN   node_modules/typesafe-routes
npm WARN     typesafe-routes@"*" from the root project

This is likely because I'm using typescript 5.x.x and your dependence peerDependencies are:

https://github.com/kruschid/typesafe-routes/blob/master/package.json#L36

```json
  "peerDependencies": {
    "typescript": "^4.1.0"
  },
```

you should replace with:

```json
"peerDependencies": {
  "typescript": ">=4.1.0"
},
```
i.e. any typescript version above or equals to 4.1

**Comment by kruschid** [comment]
Thank you for reporting @Xample 

Please try v10.0.6 and let me know if you encounter any problems.

**Comment by Xample** [comment]
It works, thank you
