### ISSUE TITLE
Proper way to compose routes

### ISSUE THREAD

**Issue by Xample** [kruschid/typesafe-routes#51]
Hello,
in our project we do organise feature folders with all its dependencies so that we can share a feature folder between projects. Something like that:

```typescript
import { createRoutes, int, RouteNodeMap } from 'typesafe-routes';

// feature/user.route.ts folder
export const Users = {
    list: {
        path: ['list'],
    },
    detail: {
        path: ['detail', int('uid')],
  },
} satisfies RouteNodeMap;

// feature/cart.route.ts folder
export const Cart = {
  detail: {
    path: ['detail'],
  },
} satisfies RouteNodeMap;


// app.route.ts folder
export const routes = createRoutes({
    user: {
        path: ['user'],
        children: Users,
    },
    cart: {
      path: ['cart'],
      children: Cart,
  },
});
```

I expected to be able to put a routeContext into another routeContext but it seems no to be possible (and there is no toRouteNodeMap converter (?)) so is there another way to compose routes or we are doing it the right way ?

**Comment by Xample** [comment]
ok, to what I've seen, I should export the `RouteNodeMap` from my module which could be imported and included within the RouteNodeMap of another module and then always use the createRoutes to create / parse urls

**Comment by kruschid** [comment]
> ok, to what I've seen, I should export the `RouteNodeMap` from my module which could be imported and included within the RouteNodeMap of another module and then always use the createRoutes to create / parse urls

Right, this is one possible method.

I've written about [composing routes on this documentation page](https://github.com/kruschid/typesafe-routes/blob/91be1e4ce079cbc31f84f7a127d9f1e1e9a5f663/docs/advanced-features/composing-routes.md). It could be an interesting alternative. I hope you don't mind me using your scenario as inspiration for my example there.
